### ISSUE TITLE
Server stops working after arbitrary amount of time

### ISSUE THREAD

**Issue by lucasfcnunes** [ksurl/docker-flexget#19]
Web server suddenly drop, and tasks don't run. 
*It has happened several times before.

(I'LL ADD DETAILS HERE LATER WHEN IT HAPPENS AGAIN AS I DIDN'T SAVE THE LOGS)

**Comment by ksurl** [comment]
I'd open a ticket on the main flexget repo. They actually have an official image now also.

**Comment by lucasfcnunes** [comment]
I just switched to theirs (on your indication), so I'm closing this. Thanks for the indication!
--
For reference if someone wants to commute too:
https://flexget.com/InstallWizard/Docker
