### ISSUE TITLE
Missing webui in latest docker (docker pull ksurl/flexget:6.1.5)

### ISSUE THREAD

**Issue by ollejacobsen** [ksurl/docker-flexget#25]
Seems like the webui isn't built/included in the latest version (docker pull ksurl/flexget:6.1.5).
Upgraded my docker image and get the message

**From logs**
```
2022-12-13 23:23:41 CRITICAL webui                         Failed to start web ui, this can happen if you are running from GitHub version and forgot to run the web ui build, see https://flexget.com/Web-UI for instructions
```

**From webui endpoint**
```
Failed to load Flexget Web UI

It looks like you are running flexget from the GitHub source. If you want to use the webui you'll have to run the WebUI build steps by following https://flexget.com/Web-UI
```

Let me know if I can help out in any way. 

Thanks in advance.

**Comment by ksurl** [comment]
I found the issue. since the base image was updated to python 3.11, the webui path changed. Should be fixed. Try repulling the image for v6.1.5. Also fyi, the official flexget repo has an official docker image as well now.

**Comment by ollejacobsen** [comment]
Superb, that was a quick fix. Can confirm that it works as expected.

Thanks for the heads up about the official image. I've missed that. Been using yours all the time and didn't have a need to find another.

Good work 👍 

Cheers!

**Comment by ollejacobsen** [comment]
Can confirm that it works as expected
